# Base layer
FROM node:18.14.1

# Set the working directory 
WORKDIR /app

# Copy over dependency files 
COPY package.json package-lock.json ./

# Install 
RUN npm ci

# Copy over next.js config 
COPY next.config.js ./next.config.js

# Copy all files 
COPY . .

CMD ["npm", "run", "dev"]
