version: '3'

services:
  backend:
    container_name: ddgh-backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
      - ./backend/nodemon.json:/app/nodemon.json
      - /app/node_modules
    command: npm run dev
    env_file: .env
    environment:
      - NODE_ENV=development
    networks:
      - ddgh

  frontend:
    container_name: ddgh-frontend
    restart: unless-stopped
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src/ # mounted whole src to avoid missing reload on new files
      - ./frontend/public:/app/public
    env_file: .env
    environment:
      - NEXT_PUBLIC_ENV=development
    networks:
      - ddgh

networks:
  ddgh:
